DS_SKIP_CUDA_CHECK=1 accelerate launch --config_file zero2.yaml full_finetune_base_qat.py \
	--model_name_or_path Qwen3-4B-250426 \
	--data_path sft.json \
	--bf16 True \
	--output_dir output_qat \
	--num_train_epochs 1 \
	--per_device_train_batch_size 2 \
	--per_device_eval_batch_size 1 \
	--gradient_accumulation_steps 16 \
	--save_strategy "steps" \
	--save_steps 500 \
	--save_total_limit 3 \
	--learning_rate 1e-5 \
	--weight_decay 0.00 \
	--adam_beta1 0.9 \
	--adam_beta2 0.999 \
	--seed 43 \
	--load_from_gptq false \
	--gptq_path qwen2.5_3b_gptq/pytorch_model.bin \
	--load_from_qat false \
	--qat_path None \
	--warmup_ratio 0.01 \
	--lr_scheduler_type "cosine" \
	--max_grad_norm 1.0 \
	--logging_steps 1 \
	--gradient_checkpointing true \
	--report_to "none"
